### PR TITLE
Chore: Require newer ayon core

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Description
After PR https://github.com/ynput/ayon-core/pull/295 the addon require ayon-core > 0.4.0 .

## Additional information
This should be already part of that PR and ayon-houdini release 0.3.9 .

### CODE REVIEW

**Review by BigRoy — APPROVED** [review]
Description and change makes sense - I'm not sure how to confirm the compatibility check itself actually works but I suppose that's an existing feature that we know should work?

**Comment by iLLiCiTiT** [comment]
> Description and change makes sense - I'm not sure how to confirm the compatibility check itself actually works but I suppose that's an existing feature that we know should work?

Happens on bundle creation on AYON server.

**Comment by BigRoy** [comment]
So I tested this out and it does work:

image
image
image

However, the PR description makes it sound like anything ABOVE 0.3.9 should be fine - but the compatibility check only allows **above** 0.4.0 and does not allow exactly 0.4.0. Is that correct?

**Comment by iLLiCiTiT** [comment]
>  but the compatibility check only allows above 0.4.0 and does not allow exactly 0.4.0. Is that correct?

It should allow greater than 0.4.0 . Core release 0.4.0 does not contain changes that current houdini develop requires. The changes are in current develop of core addon.

**Pull request merged**
