### PR TITLE
174 cleanup pointcache and model families

### LINKED ISSUE #174: Cleanup pointcache and model families
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

### Please describe the feature you have in mind and explain what the current shortcomings are?

- Clean up the pointcache and model families.
- use `get_publish_families`
- remove collect_instances_type.py collector plugin

### Suggested implementation?

.

### Describe alternatives you've considered:

.

### PR DESCRIPTION
**Pull request by MustafaJafar**
## Changelog Description
resolve #174 

> [!Note] 
> This is a smaller version of https://github.com/ynput/ayon-houdini/pull/149 without the changes related to deadline.

## Testing notes:
1. publishing pointcaches and model should work as before.

### CODE REVIEW

**Review by BigRoy — APPROVED** [review]
Looks good to me.

I actually think this is ALSO a good moment to start changing the `bgeo` and `abc` family to `rop.geometry` and `rop.alembic`. What do you think?

**Comment by MustafaJafar** [comment]
> Looks good to me.
> 
> I actually think this is ALSO a good moment to start changing the `bgeo` and `abc` family to `rop.geometry` and `rop.alembic`. What do you think?

`rop.geometry` is also used for exporting vdb caches.

**Comment by moonyuet** [comment]
> > Looks good to me.
> > I actually think this is ALSO a good moment to start changing the `bgeo` and `abc` family to `rop.geometry` and `rop.alembic`. What do you think?
> 
> `rop.geometry` is also used for exporting vdb caches.
> 
> I think I'll enjoy doing some cleaning up.

we can have `rop.vdb` family for exporting vdb, instead of `rop.geometry`.

**Review by moonyuet — APPROVED** [review]
Looks good for me. And guess it is ready for the merge?

**Pull request merged**
